//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYMATHANG
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public int ID { get; set; }
        public string MAHANG { get; set; }
        public string TENHANG { get; set; }
        public int SOLUONG { get; set; }
        public int GIATIEN { get; set; }
        public byte[] ANH { get; set; }
    }
}
